name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./*.pickle
            ./*.db.*
            ./public
          key: ${{ runner.os }}-miyadaiku

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x

      - name: Install dependencies
        run: make pip-install

      - name: Build
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: aoirint.com
